### ISSUE TITLE
Can we add 'convert' package to application vm?

### ISSUE THREAD

**Issue by gregharvey** [codeenigma/ce-vm#13]
Hi,

Client has asked:

> Is it possible to have 'convert' installed on to the vm, so we have the same imagemagick setup on all our environments?

I guess it is, thought a GitHub issue makes most sense! :-)

Thanks,

Greg

**Comment by pm98zz-c** [comment]
You can already add anything you want through the use of custom roles. Have a look in the "examples" folder at the php-imagick one, for example.
To make thing easier, I'll add soon a generic role so you can just list additional packages in the config file, it's ready to go but I need to test it before pushing.
