### ISSUE TITLE
Tests are currently no reliable

### ISSUE THREAD

**Issue by pm98zz-c** [codeenigma/ce-vm#54]
When running tests through Travis for a PR, we actually don't run the tests on the right branch. The current major branch is harcdoded in https://github.com/codeenigma/ce-vm/blob/5.x/tests/test.sh#L30, leading to tests to be run against it instead of the target branch.
We should instead use the current branch (see https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/ and https://github.com/travis-ci/travis-ci/issues/6652) when available.
We can use that in 2 ways: 
- we create a matching branch in ce-vm-model before each PR and adjust the file accordingly.
- we replace the branch (sed or something) in the file from the main branch (probably better).

**Comment by vengador** [comment]
@pm98zz-c In the second option, are you suggesting to take the current branch from ce-vm repo (if we suppose as convention we will use as branch name 5.x-BRANCH_NAME), remove part of the name after - and use it as branch in ce-vm-model repo?
