### ISSUE TITLE
Error response from daemon: endpoint with name ***** already exists in network

### ISSUE THREAD

**Issue by vengador** [codeenigma/ce-vm#76]
When I try to do a vagrant up, I receive an error:

> Stderr: Error response from daemon: endpoint with name ***** already exists in network ce-vm-192.168.57.0/24

If I retry vagrant up, it works correctly but it fails in the next docker machine. I have tried removing network and containers but it doesn't solve the problem.

**Comment by pm98zz-c** [comment]
This has been fixed in last version
